-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgJkidK1fPKcnhrUwg
qh1K54V/uw4eV2wBzAWi2+FbFiOgCgYIKoZIzj0DAQehRANCAARjkSGQ9oPY2onu
EX7JF/+mBioKfqDHnv5gJLudiMSMw9Ij6mQIO5I/ek4DxOlR5bQP4BEEzCcBLJ9n
f8+vfqmd
-----END PRIVATE KEY-----