# platform :ios, '15.0'
platform :ios, '15.0'

target 'LocatedApp' do
  # Use static frameworks
  use_frameworks! :linkage => :static

  # Firebase Pods
  pod 'Firebase/Auth'
  pod 'Firebase/Core' # Core is often a dependency, good to have it explicit
  pod 'Firebase/Firestore'
  pod 'Firebase/Functions'
  pod 'Firebase/Messaging' # The new pod for notifications
  
  # Google Sign-In - use version compatible with current Firebase
  pod 'GoogleSignIn', '~> 6.2'

  target 'LocatedAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LocatedAppUITests' do
    # Pods for testing
  end

end

# Post-install script to fix build issues
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # Fix deployment target warnings by setting minimum to 15.0
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      
      # Comprehensive BoringSSL-GRPC fix
      if target.name.start_with?('BoringSSL-GRPC')
        # Completely reset all compiler flags to remove problematic -G flags
        config.build_settings.delete('OTHER_CFLAGS')
        config.build_settings.delete('OTHER_CPLUSPLUSFLAGS')
        config.build_settings.delete('OTHER_LDFLAGS')
        config.build_settings.delete('WARNING_CFLAGS')
        config.build_settings.delete('GCC_WARN_INHIBIT_ALL_WARNINGS')
        
        # Set clean compiler flags
        config.build_settings['OTHER_CFLAGS'] = ['-DBORINGSSL_PREFIX=GRPC', '-w']
        config.build_settings['OTHER_CPLUSPLUSFLAGS'] = ['-DBORINGSSL_PREFIX=GRPC', '-w']
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] = ['$(inherited)', 'BORINGSSL_PREFIX=GRPC']
        config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = 'YES'
        
        # Force disable all debug and optimization flags that might contain -G
        config.build_settings['GCC_OPTIMIZATION_LEVEL'] = '0'
        config.build_settings['GCC_GENERATE_DEBUGGING_SYMBOLS'] = 'NO'
        config.build_settings['DEBUG_INFORMATION_FORMAT'] = ''
        config.build_settings['DEPLOYMENT_POSTPROCESSING'] = 'NO'
      end
      
      # Fix gRPC issues
      if target.name == 'gRPC-Core'
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'GRPC_CFSTREAM=0'
      end
    end
  end
  
  # Additional fix: modify the Pods project build settings directly
  installer.pods_project.build_configurations.each do |config|
    config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
  end
end

